### ISSUE TITLE
Issues with opencore.slowgeek.com

### ISSUE THREAD

**Issue by Dids** [rlerdorf/OCSanity#14]
Not sure if you're the one hosting the sanity checker, but clicking on the right-side results (recent checks) will redirect to some random website (looks like a scam).

Additionally, the "recent checks" sidebar seems to be loading a _massive_ amount of data, so not sure if there's supposed to be a maximum set on that? This is causing the website to load very slowly and also scrolls almost infinitely.

**Comment by rlerdorf** [comment]
Yeah, someone has been spamming it uploading plist files that has an xml hack that redirects to some site in it. I will add a filter for it and an ip block for these idiots.

**Comment by Dids** [comment]
Sorry to hear that, but very glad to hear that you're aware of the issue. Thanks, both for `OCSanity` and for maintaining the website!

**Comment by Dids** [comment]
Seems to be fixed now, thanks again!
