### ISSUE TITLE
'MemoryFormFactor' mention in 'Generic' section

### ISSUE THREAD

**Issue by vovinacci** [rlerdorf/OCSanity#17]
Hi,

  First of all, thanks a lot for the wonderful tool!

  Found small issue. When checking configuration for `CoffeeLake` and OC `0.6.2`, got a remark on `Generic` section
```
MemoryFormFactor is missing. Normally set to Auto
```

Going through OC configuration/documentation, the only mention I can found is in `SMBIOS` section
```
MemoryFormFactor
Type: plist integer, 8-bit
Failsafe: OEM specified
SMBIOS: Memory Device (Type 17) — Form Factor
Description: Memory form factor. On Macs it should be DIMM or SODIMM.
```
https://github.com/acidanthera/OpenCorePkg/blob/0.6.2/Docs/Configuration.tex#L4931-L4937

This change is introduced in https://github.com/rlerdorf/OCSanity/pull/16 by @khronokernel 
Looking through https://dortania.github.io/ - wasn't able to find the reference as well.
This seems to be a typo or copy-pasta of some kind. If this is the correct assumption, can prepare a PR to fix this.

Thanks in advance!

**Comment by khronokernel** [comment]
Ah it's a typo, supposed to be SystemMemoryStatus. Can fix that in a sec

**Comment by vovinacci** [comment]
@khronokernel Thanks much again for the speed of light reaction and fix!

**Comment by rlerdorf** [comment]
merged
