### ISSUE TITLE
OpenCore 0.6.4 support is missing

### ISSUE THREAD

**Issue by ghost** [rlerdorf/OCSanity#23]
Hello. I've been checking your web site for two days to verify the new config file, but I don't see the current OpenCore version. When will it be ready?

**Comment by jaylex32** [comment]
no 0.6.4 version on the website, please fix.

**Comment by rykr** [comment]
bump

**Comment by neemagha** [comment]
bump

**Comment by taeyeonssupdate** [comment]
bump

**Comment by dstyp** [comment]
This should be closed(?)
Support exists. You can clone the repo for the latest version and it will have 064.

**Comment by taeyeonssupdate** [comment]
> This should be closed(?)
> 
> Support exists. You can clone the repo for the latest version and it will have 064.
> 
> 

I think website is for non-programmer just upload config to check setting, so need someone restart server.

**Comment by ghost** [comment]
Okay, now it seems that the web site is updated. Thank you.
