### ISSUE TITLE
0.6.7 ?

### ISSUE THREAD

**Issue by mrgooge** [rlerdorf/OCSanity#26]
Any new data for the latest OC release  0.6.7 ?

**Comment by neemagha** [comment]
Please update the website to check for 0.6.7. Thank you.

**Comment by ickc** [comment]
@neemagha, can you not spam us? You statement is exactly the same as the OP. If you feel you need to "+1" on the same request then you can use the "pick your reaction" icon there, which will not trigger an email to all of us like your reply.

Please respect [GitHub etiquette like this one](https://github.com/kossnocorp/etiquette). (No one made those rules, but they are just common sense on GitHub.)
Not only you are spamming the maintainer, but also any of the subscribers that want to know the development on this like me.

**Comment by ghost** [comment]
Is there any update about this?
