### ISSUE TITLE
0.6.0 UEFI additions

### ISSUE THREAD

**Issue by idcrook** [rlerdorf/OCSanity#9]
Seeing messages with checker on 0.6.0 https://opencore.slowgeek.com/?file=xxx&rs=haswell060

- You should have exactly 10 settings in the UEFI/Output section
- You should have exactly 15 settings in the UEFI/ProtocolOverrides section

OpenCore 0.6.0 added:

> config.plist -> UEFI -> Output - Missing Key: UgaPassThrough
> config.plist -> UEFI -> ProtocolOverrides - Missing Key: AppleFramebufferInfo

meaning 

 `UEFI -> Output` now has 11 settings
 `UEFI -> ProtocolOverrides ` now has 16 settings

**Comment by rlerdorf** [comment]
fixed
